### ISSUE TITLE
Simpler todo list integration

### ISSUE THREAD

**Issue by codingcarpenter** [alagrede/znote-app#17]
ToDo list syntax already exists in the Markdown capabilities with the following syntax

`- [ ] Item to do` and to show its checked off `- [X] Completed` but this is a bit cumbersome when trying to rapidly mark down objectives while taking notes during a live meeting or event.

It would be great if this could be integrated in a block like syntax used for the other apps such as mermaid, so that it would be a more simplistic dash or the like.

If its possible, being able to check off items and have it update your markdown with a strike through that would also be fantastic but thats really more of a cool to have item.

**Comment by alagrede** [comment]
@codingcarpenter 
Finally! Will be deployed this Sunday! 🎉
![todolist-editable](https://user-images.githubusercontent.com/5312754/122576891-798b4c80-d052-11eb-8085-77bdce949de3.gif)

**Comment by hakimio** [comment]
@alagrede minor request: can you also make the checkboxes themselves clickable as well? Intuitively I click on the checkbox icon instead of the text.

**Comment by alagrede** [comment]
Hello @hakimio,
I'm sorry, I tried to make the checkbox also clickable but I have a weird bug with the DOM. I cannot doing it now. Too expensive in terms of time.

**Comment by hakimio** [comment]
Ok, fair enough. Just one more small request then: can you leave the old behavior where completed items were not striked-through? Or make this feature optional? It makes reading completed items a bit tricky.

**Comment by alagrede** [comment]
Ok I'll add an option for next release. 👍
