### ISSUE TITLE
Cursor calibration is to high.

### ISSUE THREAD

**Issue by brunogoossens** [alagrede/znote-app#2]
I need to click the line high to get the correct cursor position. If I hit the line to low, the line below is selected.

I'm running the app om macOS.

![cursor (1)](https://user-images.githubusercontent.com/1636664/90290415-22d74400-de7e-11ea-9b7d-0374962e03bc.gif)

**Comment by alagrede** [comment]
Hello @brunogoossens, 
Thanks for your report, the fix is now available and deploy.
Sincerely.
