### ISSUE TITLE
Opening the app just shows a white screen and need to force quit to close

### ISSUE THREAD

**Issue by jameshone** [alagrede/znote-app#20]
I have a macbook pro. Cannot debug due to  the devtools not opening either. This occurs on the `znote-0.6.6-lab-preview.dmg` package

**Comment by alagrede** [comment]
Hello James,
I'm sorry you are having trouble. 😣
It seems like an initialization problem. To help me investigate this issue and help you, could you please answer these questions:
- Have you created a Cloud account?
- Does the problem occur every time?
- Do you have an active internet connection?
- Have you moved several files on your Mac that are already open in Znote?

As a last resort, you can move the `/Users/YOURNAME/Library/Application\ Support/znote/user-preferences.json` file to reset the application.(Make a copy)
it is also possible to tweak the file to repair the application.

Thank you James for your precious help.

**Comment by hakimio** [comment]
Fixed now?

**Comment by alagrede** [comment]
Hello @hakimio
I'm still waiting for @jameshone responses to be sure I resolve this issue.
I've done a lot of work since version 0.6.6 and probably fixed it already.

**Comment by alagrede** [comment]
No response to this thread. I consider it's now fixed in anterior release.
