### ISSUE TITLE
Note is not synced

### ISSUE THREAD

**Issue by hakimio** [alagrede/znote-app#21]
- I have enabled server sync on mobile app
- Used a desktop app to create a new note
- After creating a new note, I enabled server sync on desktop app as well
- Now it doesn't want to upload the note which I created before turning on server sync

Can I force it to upload the note or do I have to create a new one for it to upload the note?
OT: do you plan to have a paid version with higher server sync limit?

**Comment by hakimio** [comment]
My bad. Didn't know that you have to press that button for every note you want to sync.

**Comment by alagrede** [comment]
You're welcome. I mean the UX could be improved!

**Comment by hakimio** [comment]
Yeah, talking about UX. Might be a good idea to get rid of the toggle button for switching between dark and light modes and just use the icon itself as a button. At least for me, it's a bit confusing when all the other buttons are icons. Also, imho that toggle switch seems to be out-of-place.
