### ISSUE TITLE
Top bar orange background in "light" mode too bright

### ISSUE THREAD

**Issue by hakimio** [alagrede/znote-app#22]
It would be nice if you used some not so bright background color for top bar when the app is used in "light" mode (for example, light grey you use for selected note). It's pretty annoying at least for me.

**Comment by alagrede** [comment]
Yes 😅 I understand that it can be boring.
I will change it to a lighter color as you recommend for the next version.

**Comment by hakimio** [comment]
I guess this is done now. You just haven't updated the `README` yet.

**Comment by alagrede** [comment]
Hello @hakimio Yes you're right, I forgot to mention it in the release notes.
