### ISSUE TITLE
[Regression] Checkbox issue in v0.7.7

### ISSUE THREAD

**Issue by hakimio** [alagrede/znote-app#27]
Here is how checkboxes look like after the last update (v0.7.7):

![image](https://user-images.githubusercontent.com/768105/122554809-bd258c80-d039-11eb-9099-b161ac93358c.png)

**Comment by alagrede** [comment]
Ouch ... Seems to be a regression from the underlying lib. I'm working on it.
Thanks!

**Comment by alagrede** [comment]
Well this is fixed. I am waiting for Sunday to deploy in order to give myself time to do other tests.

**Comment by alagrede** [comment]
Also a bonus: https://github.com/alagrede/znote-app/issues/17
