### ISSUE TITLE
Feature request: Persist view mode

### ISSUE THREAD

**Issue by brunogoossens** [alagrede/znote-app#3]
Hey,

Thanks for all the work on Znote. Loving the app and using it daily!

I have a feature request of a small improvement of the app.
It would be nice to use the view mode that was last used after reopening the app.

![Screenshot 2020-11-15 at 12 27 58](https://user-images.githubusercontent.com/1636664/99183761-7fc4ed80-273e-11eb-80a0-cca65eada877.png)

At the moment the view mode is always reset after reopening the app.

Kind regards.

**Comment by alagrede** [comment]
Hello @brunogoossens,

Sorry for the delay, we have lot of work with the new Apple M1 support. 
The view mode is now persisted and a full screen markdown viewer (for presentation) will be available is the next version.
Stay tuned, a major version is coming soon with lot of improvements and a free mobile app.

Best regards,
