### ISSUE TITLE
Mermaid error

### ISSUE THREAD

**Issue by LuigimonSoft** [alagrede/znote-app#33]
when I write ```mermaid I get an error message Syntax error in graph
mermaid version 8.9.3 that does not allow to continue or close the application

<img width="899" alt="Captura de Pantalla 2021-07-22 a la(s) 10 46 08" src="https://user-images.githubusercontent.com/7293391/126668544-9e4e97bc-9450-44f2-919e-85532771e020.png">

**Comment by alagrede** [comment]
😳  Hello @LuigimonSoft,  
Thank you very much for your report. 🙏 
I recently refactored the mermaid diagram to allow export to svg.

I just published a fix in ** 0.7.18 ** you can update your app now: https://znote.io/
