### ISSUE TITLE
Note sync broken in latest version

### ISSUE THREAD

**Issue by hakimio** [alagrede/znote-app#38]
Since last update, synced notes are blank for me. Not sure if it's some migration from old version issue or it's broken in general.

**Comment by alagrede** [comment]
Hello @hakimio,
All my migration and sync tests are green.

To avoid to loose data, I left notes content into the original file
`~/Library/Application\ Support/znote/user-preferences.json`
Make a copy to ensure to keep your notes.

Could you please send me your znote account email at contact[at]alc-digital.fr I will check if I see some errors on your account.

**Comment by alagrede** [comment]
Thank you for help @hakimio 🙏 
I just released  a version **1.0.1**. Please update.

I did find a vicious bug that can cause notes to dump during migration with synchronization enabled.
Unfortunately I cannot re-import the notes. Instead, I suggest that you manually retrieve your empty notes using the script below:
1- Open the attached file with znote [migration-fix.md](https://github.com/alagrede/znote-app/files/7143271/migration-fix.md)
2- Execute the first block to load the filename var
3- Execute the second block to list your notes
4- Change the noteID to retrieve the value in the 3rd block
5- Reinsert the value in the original note


### URL of your znote file
```js
//global 1
const filename = "/Users/USERNAME/Library/Application\ Support/znote/user-preferences.json";
```

### List old notes
```js
const data = _fs.readFileSync(filename, 'utf8');
const json = JSON.parse(data);
json.notes.forEach(n => print(`id: ${n.id}, name: ${n.filename}`));
```

### Read a note value by Id
```js
const noteId="_34j15g1aq";
const data = _fs.readFileSync(filename, 'utf8');
const json = JSON.parse(data);
const note = json.notes.filter(n => n.id === noteId)[0];
print(note.value);
```

**Comment by hakimio** [comment]
@alagrede Thank you. I managed to recover the missing notes. Feel free to close the issue.

Here is a simple nodejs script which will list all notes with their content if anyone else has to deal with this issue:
```js
const fs = require('fs');

// Full path to "user-preferences.json"
// Windows: "C:\\Users\\USERNAME\\AppData\\Roaming\\znote\\user-preferences.json"
// Linux:  "/Users/USERNAME/Library/Application\ Support/znote/user-preferences.json"
const filename = "user-preferences.json",
    data = fs.readFileSync(filename, 'utf8'),
    json = JSON.parse(data);

json.notes.forEach(
    n => console.log(`\n\n\n\n===> ${n.filename}\n\n`, n.value)
);
```

**Comment by alagrede** [comment]
Great. Thank you for the script!
