### ISSUE TITLE
Not converting tabs to spaces

### ISSUE THREAD

**Issue by manngo** [alagrede/znote-app#39]
Is there an option not to convert tabs to spaces?

**Comment by alagrede** [comment]
Hello @manngo,
Ok. I will add an option to choose between tab or x spaces for the next release.

I will update the issue when it's done.

Anthony

**Comment by manngo** [comment]
That’s great! Looking forward to it.

**Comment by alagrede** [comment]
Added new editor options with 1.1.2
Hope this will help you.

<img width="652" alt="editor-options" src="https://user-images.githubusercontent.com/5312754/141687769-af63cc2d-3109-4d06-89a0-bd379fd7ac02.png">

**Comment by manngo** [comment]
> Added new editor options with 1.1.2 Hope this will help you.

That works perfectly! Thanks.
