### ISSUE TITLE
Cannnot open znote anymore

### ISSUE THREAD

**Issue by jameshone** [alagrede/znote-app#43]
As of today I am informed that znote will damage my mac when trying to open it.
See attached screenshot

[](url
<img width="1182" alt="Screenshot 2021-12-09 at 22 10 12" src="https://user-images.githubusercontent.com/1188615/145469549-44b23826-55cf-426f-a185-e7620c8c3b41.png">
)

**Comment by alagrede** [comment]
Hello @jameshone,
Thank you for your alert. I'm currently renewing certificates expiring today.
I am so sorry for this inconvenience 😓
I am preparing a new version as soon as possible.

**Comment by alagrede** [comment]
Should be ok now but unfortunately you need to update to the last version:
https://znote.io/download-lab.html#mac

**Comment by jameshone** [comment]
It's work as expected, Thanks!
