### ISSUE TITLE
Error Messages and console logs

### ISSUE THREAD

**Issue by seigel** [alagrede/znote-app#53]
I am trying to figure out why my mermaid diagrams are NOT working when using subgraphs and direction directives.  I was wondering if there is a place where error messages from mermaid compile syntax errors might show up.

**Comment by alagrede** [comment]
Hi @seigel,
Yes, when I integrated the siren, I hadn't found a clean way to detect errors without crashing the whole application.
I agree, I should show errors somewhere to help during conception. I will plan to review this behavior very soon.
Thanks for your feedback.
We keep in touch.
Anthony

**Comment by alagrede** [comment]
Done! Coming soon.
