### ISSUE TITLE
Object type can not be displayed properly

### ISSUE THREAD

**Issue by browneyedsoul** [alagrede/znote-app#59]
It just show `[object Object]` please fix this!

**Comment by alagrede** [comment]
Hi @browneyedsoul,

What are you trying to display? The `print()` method currently show primitive types.
To display an object you can use the default method: `printJSON` which use `JSON.stringify(json, null, 2)`

I hope I helped you 😊
Anthony

**Comment by browneyedsoul** [comment]
!!!!!!!!!!!!

Thank you so much! I should've read document closely..! 🙈

Your product is super amazing thank you again!

**Comment by alagrede** [comment]
Thank you very much 🙏
If you have any other question, you can also open a discussion here: https://github.com/alagrede/znote-app/discussions
I will my best to help you.
