### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by benharvie** [alagrede/znote-app#74]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@rezaduty) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by alagrede** [comment]
Hello @benharvie,
As advised I just added a `SECURITY.md` file with an email to contact me.
email: contact[at]alc-digital.fr

I'm waiting for your contact.
Thank you for your help 🙏.

**Comment by rezaduty** [comment]
Hello @alagrede,

Can you please request for cve

Thank You

Regard

**Comment by psmoros** [comment]
> Hello @alagrede,
> 
> Can you please request for cve
> 
> Thank You
> 
> Regard

Hey Anthony! If you just give us the okay we'll go ahead and issue a CVE for @rezaduty over on huntr.dev where this vulnerability was found

**Comment by psmoros** [comment]
Hey Anthony! Ofc, sorry for the confusion. The vulnerability has reached the end of its lifecycle but researchers are really motivated when theirs report gets a CVE (Certificate of Vulnerability Exposure). 
CVEs are serial numbers within the National Vulnerability Database (US DoD) that advises your downstream users that a vulnerability has been found in a specific version and that they should upgrade (delivered by GitHub's dependabot).
@rezaduty just needs a CVE to advance their career as a researcher but wether you want to go ahead with it (nothing to do from your side) is in your hands.

**Comment by alagrede** [comment]
Ok @psmoros, thanks for your explanation. Just because you helped me improve the general security of the application, of course you can issue a CVE if that helps.

**Comment by psmoros** [comment]
Thank you :))

**Comment by attritionorg** [comment]
CVE = Common Vulnerabilities and Exposures, not "Certificate of Vulnerability Exposure"
