### ISSUE TITLE
Issues with mermaid graph

### ISSUE THREAD

**Issue by lems3** [alagrede/znote-app#76]
Hi!

I tried to build a mermaid graph with subgraph, and I get the error "Cannot set property 'rank' of undefined".

I've build an example of what causes the issue on an online live editor for easier comparison : https://mermaid.live/edit#pako:eNpVUktuwjAQvcrIi9JKoO5ZVEqgi6qiQg3QBelisAdwm9jBH1SEOBDn4GIdk4iqXljjz5v3sY9CWkViKDYOmy3MxqUBHtmyFO-Xs6QmaGtAEVTIc42Gy_s3-gmwIQPj4uWhFJ8dBgYDKEU-LwVXT5Avi2DdARQaDxVFByuU35XdpHb5_D9q9NyhRsuCKqb84-uDtzrcwNLWdTRgIzSWe_K9fM6bRpIzl3PX1cdVayjLYDl12jrtMVnpzpk3Sx4LDbtIPp341JIJeZ0Eqss5oK4827vqWqREyDBRcAS4J8meYPI6AwqPjGQdPjgMtzjIqLbI4Q5G1x5Z1u4sWs_jNhiQ6EH1oqFbwk0VPWyc9Z7ds9nG2S8KXUIfrGTqrCTvYwLa9dpdJXtyey0ZjRxL73LeRd0QpGRZkuiLmlyNWvFjH5OOUoQt1VSKIZeK1hgrpijNia9iDLY4GCmGwUXqi9goDDTWyKnWYrjGipUJUppfeNJ-oOs_Ov0CIJrATg

From what I could understand, pointing to or from a subgraph seems to causes the issue. I can skip the issue by pointing to an element in the subgraph, but my first goal was to skip having one rectangle that get multiple elements pointing to it as it's a "category" of elements.

Not an urgent bug, but if you planned an update to the software, if it could be looked at it would be nice.

Thanks!

Note : I couldn't find which version of zNote I'm at. Is there a way to find it ?

**Comment by alagrede** [comment]
Hi @lems3,
Thank you for your report. I probably need to upgrade to mermaid lib. I will take a look for the next update!
Anthony

**Comment by alagrede** [comment]
It's coming soon.

<img width="1410" alt="mermaid-update" src="https://user-images.githubusercontent.com/5312754/211806254-52bedc4e-3943-4e51-a2aa-749d046151f0.png">

**Comment by alagrede** [comment]
Fixed with **V2.0.2**

**Comment by lems3** [comment]
Just did the uptade, I can confirm it works. Thanks 😃
