### ISSUE TITLE
The mermaid diagrams don't work

### ISSUE THREAD

**Issue by LuigimonSoft** [alagrede/znote-app#78]
When i try to create a mermaid diagram with ```mermaid the editor does not recognize it and does not create the graph

**Comment by alagrede** [comment]
Hi @LuigimonSoft,
Should only work if you have Dev mode enabled (bottom right).
Regards

**Comment by alagrede** [comment]
Could you confirm me?

**Comment by LuigimonSoft** [comment]
Oops sorry it is true with dev mode the mermaid diagram is not working and i don't know it but without dev mode is working, thank you

**Comment by alagrede** [comment]
Cool 👍 You're welcome.
