### ISSUE TITLE
Linux application layout 

### ISSUE THREAD

**Issue by linesquarecube** [alagrede/znote-app#79]
Hi, first of all - great app!
One thing which I would like to be improved is the look in Linux. As I'm using Gnome, the style with angular corners and the Windows style min/max/close buttons do not really fit. Would it be possible to have a style similar to the shown screenshots from Mac? This would suit better IMO.

Thanks for looking into this :)

**Comment by alagrede** [comment]
Hi @linesquarecube,
Thank you 🙏
Yes, I know I share the same style with Windows and Linux. I plan to change that soon.

Best Regards

**Comment by alagrede** [comment]
You're in luck. This will be done in the next version. 😊

**Comment by linesquarecube** [comment]
Thanks for this fast implementation :smiley: 

Version 2.1.2 now has native window decoration, but unfortunately the window stays blank and I have to kill the process to end znote. Is there any new dependency I have to install? 

Some information regarding my system:
```
      _,met$$$$$gg.           linesquarecube@debian-yoga 
    ,g$$$$$$$$$$$$$$$P.       ----------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: 20LH000NGE ThinkPad X380 Yoga 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-5-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 5 days, 56 mins 
 $$P      d$'     ,    $$P    Packages: 3262 (dpkg), 21 (flatpak) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1200 
 Y$$.    `.`"Y$$$$P"'         DE: GNOME 43.3 
 `$$b      "-.__              WM: Mutter 
  `Y$$                        WM Theme: Adwaita 
   `Y$$.                      Theme: adw-gtk3 [GTK2/3] 
     `$$b.                    Icons: Adwaita [GTK2/3] 
       `Y$$b.                 Terminal: xfce4-terminal 
          `"Y$b._             Terminal Font: DejaVu Sans Mono 10 
              `"""            CPU: Intel i5-8250U (8) @ 3.400GHz 
                              GPU: Intel UHD Graphics 620 
                              Memory: 6408MiB / 7708MiB 
```
...and a screenshot of the blank znote window:

![grafik](https://user-images.githubusercontent.com/81855936/225050291-9bcddcb4-a32a-4204-a2c1-2379c6801a42.png)

**Comment by alagrede** [comment]
Hi @linesquarecube 👋,
I'm not sur why you have a blank window. Maybe you previously had a crash or something...
Try to **move your database** outside and **restart the app**.
```bash
mv ~/.config/znote/znote.db . 
```
If it works, your database is probably corrupted.
In this case, try to open your DB with a SQL viewer like _sqlitebrowser_
`sudo apt install sqlitebrowser`
`sqlitebrowser ~/.config/znote/znote.db` and check if you have a **record** with a NULL id or something like that. Set the NULL **id** with a random value and restart the app.

Let me know if this is a case of corruption, if so I will investigate to make sure this issue does not happen again.

PS: To avoid losing data, you will find a backup section in the settings to export all your data in a zip archive.

 Best regards
Anthony

**Comment by niecw** [comment]
Hi, I experience similar (or the same?) problem where the znote screen is blank.  I'm using different flavour of Linux, using KDE Plasma, and was running v2.1.4 of znote.

For me, there is no `~/.config/znote/znote.db` file generated, even.  The error stops at :

`xxx@system /TEMP [SIGINT]> ./znote-2.1.4.AppImage --help
/home/xxx/.config/znote/user-preferences.json
/home/xxx/.config/znote/user-functions.json
Checking for update
Update for version 2.1.4 is not available (latest version: 2.1.4, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null`

The `--help` switch is irrelevent.

**Comment by linesquarecube** [comment]
Hi, sorry for not answering for a while.
I tried to check for the `znote.db` file you've mentioned, but there is none as for @niecw . As I did not had any important things in znote so far, I tried to delte the whole znote folder in `~/.config` to start from scratch. Unfortunately this did not help at all. The folder is created again after starting znote, but now there are less files than before and the screen still stays blank. The content is the following:
```
user@machine:~/.config/znote$ ls
 blob_storage     Dictionaries                Preferences       zenv
 Cache            GPUCache                    SingletonCookie
'Code Cache'     'Local Storage'              SingletonLock
'Crash Reports'  'Network Persistent State'   SS
```

The output of the terminal is the same as for @niecw
```
user@machine:~/Downloads$ ./znote-2.1.4.AppImage
/home/user/.config/znote/user-preferences.json
/home/user/.config/znote/user-functions.json
Checking for update
Update for version 2.1.4 is not available (latest version: 2.1.4, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```
Thanks for your help @alagrede :smiley:

**Comment by alagrede** [comment]
Hi @niecw, @linesquarecube  👋

I published a new version trying to fix this issue. I'm not sure, maybe a corrupt build... Could you please try if it's ok for you:
https://github.com/alagrede/znote-app/releases/tag/v2.1.5
Direct link for Linux x64 => https://github.com/alagrede/znote-app/releases/download/v2.1.5/znote-2.1.5.AppImage

**Comment by niecw** [comment]
![image](https://user-images.githubusercontent.com/594765/226889749-2ed96ca8-d238-474b-b867-0b98444897b1.png)

It loads now.  Thank you very much.

**Comment by linesquarecube** [comment]
![grafik](https://user-images.githubusercontent.com/81855936/226900713-2b9de4c5-6d90-44a1-8977-a1d388da82a1.png)
Same here :tada:
i had to delte the znote folder in `~/.config` first, but now everything is fine agian!
Thank you so much @alagrede!

**Comment by alagrede** [comment]
Thank you guys!
I will be vigilant with the next deployments to avoid this corruption.
