### ISSUE TITLE
Add znote in homebrew-cask

### ISSUE THREAD

**Issue by hkunzhe** [alagrede/znote-app#84]
Thanks for the wonderful app! I've submitted a [PR](https://github.com/Homebrew/homebrew-cask/pull/164413) to [homebrew-cask](https://github.com/Homebrew/homebrew-cask). After merged, we can easily install it with `brew install znote` 🍻.

**Comment by alagrede** [comment]
Hi @hkunzhe,
Thank you for your initiative. I never thought about installing the app through brew.

Kind regards
Anthony
